{% set name = "vasprun-xml" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vasprun-xml-{{ version }}.tar.gz
  sha256: 8862c032b8138ca2532d427ff07f5ddad48c61842f908ba9fe6938edbacb1390

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - lxml >=4.2.5
    - pandas >=0.23.4
    - numpy >=1.13.3
    - scipy >=1.1.0
    - matplotlib-base >=2.0.0
    - tabulate

test:
  imports:
    - vasprun
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/qzhu2017/vasprun
  summary: A python package for quick analysis of vasp calculation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
